//
// Created by david.zabaleta on 11/30/2020.
//

#ifndef RETO2_PROJECT_MESSAGEDECISION_CPP
#define RETO2_PROJECT_MESSAGEDECISION_CPP


enum class Chapters: char
{
    WELCOME,
    CHAPTER_1,
    CHAPTER_1_DECISION_1,
    CHAPTER_1_DECISION_2,
    CHAPTER_2,
    CHAPTER_2_DECISION_1,
    CHAPTER_2_DECISION_2,
    CHAPTER_3,
    CHAPTER_3_DECISION_1,
    CHAPTER_3_DECISION_2,
    BAD_DECISION,
    BAD_CHAPTER,
    GAME_OVER
};

#endif //RETO2_PROJECT_MESSAGEDECISION_CPP
